# Generated by Django 3.0.5 on 2020-04-08 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='set_name',
        ),
    ]
