# Generated by Django 3.0.5 on 2020-04-26 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_news_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='activate',
            field=models.CharField(default=0, max_length=30),
        ),
    ]
