# Generated by Django 3.0.5 on 2020-04-28 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='name',
        ),
        migrations.AddField(
            model_name='newsletter',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='text',
            field=models.CharField(default='', max_length=50),
        ),
    ]
