# Generated by Django 3.0.5 on 2020-04-07 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200408_0429'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='set_name',
            field=models.CharField(default='-', max_length=30),
        ),
        migrations.AddField(
            model_name='main',
            name='tel',
            field=models.CharField(default='-', max_length=30),
        ),
        migrations.AlterField(
            model_name='main',
            name='about',
            field=models.TextField(default='-'),
        ),
        migrations.AlterField(
            model_name='main',
            name='fb',
            field=models.CharField(default='-', max_length=30),
        ),
        migrations.AlterField(
            model_name='main',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='main',
            name='tw',
            field=models.CharField(default='-', max_length=30),
        ),
        migrations.AlterField(
            model_name='main',
            name='yt',
            field=models.CharField(default='-', max_length=30),
        ),
    ]
