# Generated by Django 3.0.5 on 2020-04-07 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200408_0503'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='link',
            field=models.CharField(default='-', max_length=30),
        ),
    ]
