# Generated by Django 3.0.5 on 2020-04-08 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_main_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='about',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='main',
            name='fb',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='main',
            name='link',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='main',
            name='set_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='main',
            name='tel',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='main',
            name='tw',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='main',
            name='yt',
            field=models.CharField(max_length=30),
        ),
    ]
