# Generated by Django 3.0.5 on 2020-04-19 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200419_1617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='main',
            old_name='picname',
            new_name='picnamefooter',
        ),
        migrations.RenameField(
            model_name='main',
            old_name='picurl',
            new_name='picnameheader',
        ),
        migrations.AddField(
            model_name='main',
            name='picurlfooter',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='main',
            name='picurlheader',
            field=models.TextField(default=''),
        ),
    ]
