# Generated by Django 3.0.5 on 2020-04-19 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20200419_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='picnamefoot',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='main',
            name='picnamehead',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='main',
            name='picurlfoot',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='main',
            name='picurlhead',
            field=models.TextField(default=''),
        ),
    ]
