# Generated by Django 3.0.5 on 2020-04-21 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20200419_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='aboutdetail',
            field=models.TextField(default=''),
        ),
    ]
