# Generated by Django 3.0.5 on 2020-04-26 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_main_activate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main',
            name='activate',
        ),
    ]
