# Generated by Django 3.0.5 on 2020-05-07 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_main_activate'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='seo_keyword',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='main',
            name='seo_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
